# This is a basic workflow to help you get started with Actions

name: Build & Deploy

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build code
        run: |
          npm ci
          npm run build
      
      - name: Setup _site structure
        run: |
          mkdir -p _site
          cp -r arknights _site/
          cp -r dist _site/
          cp index.html _site/
          cp index.css _site/
          cp LICENSE _site/
          cp README.md _site/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
